blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import (login_view, logout_view, register_view)
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    #url(r'^accounts/', include("allauth.urls")),
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace="posts")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/urls.py
from django.conf.urls import url
from comments.views import comment_thread, comment_delete

urlpatterns = [
    url(r'^(?P<id>\d+)/$', comment_thread, name='thread'),
    url(r'^(?P<id>\d+)/delete/$', comment_delete, name='delete'),
]

posts/api/urls.py
from django.conf.urls import url
from posts.api.views import (PostListAPIView, PostDetailAPIView, PostUpdateAPIView, PostDeleteAPIView, PostCreateAPIView)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[-\w]+)/$', PostDetailAPIView.as_view(), name='details'),
    url(r'^(?P<slug>[-\w]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[-\w]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
]

posts/urls.py
from django.conf.urls import url
from .views import (post_create,post_delete,post_details,post_list,post_update)

urlpatterns = [
    url(r'^$',post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[-\w]+)/$', post_details, name='details'),
    url(r'^(?P<slug>[-\w]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[-\w]+)/delete/$', post_delete, name='delete'),
]

comments/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
# Create your models here.

class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)
        return qs

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null=True, blank=True)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ['timestamp']

    def __unicode__(self):
        return str(self.user.username)

    def children(self):
        return Comment.objects.filter(parent=self)

    def get_absolute_url(self):
        return reverse("comments:thread", kwargs={"id":self.id})

    def get_delete_url(self):
        return reverse("comments:delete", kwargs={"id":self.id})

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
#from markdown_deux import markdown
#from django.utils.safestring import mark_safe

# Create your models here.
class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance,filename):
        return "%s/%s" %(instance.id,filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                            null=True,
                            blank=True,
                            height_field="height_field",
                            width_field="width_field")
    height_field = models.IntegerField(default=50)
    width_field = models.IntegerField(default=50)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False,auto_now_add=False)
    #read_time = models.TimeField(null=True, blank=True)
    update = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)

    objects = PostManager()


    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:details", kwargs={"slug": self.slug})

    def get_absolute_url1(self):
        return reverse("posts:update", kwargs={"slug": self.slug})

    def get_absolute_url2(self):
        return reverse("posts:delete", kwargs={"slug": self.slug})

    def get_absolute_url3(self):
        return reverse("posts:create", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-update"]

    #def get_markdown(self):
        #content = self.content
        #markdown_text = markdown(content)
        #return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_reciever, sender=Post)

comments/forms.py
from django import forms

class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea)

posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget

class Postform(forms.ModelForm):
    content=forms.CharField(widget=PagedownWidget(show_preview=False))
    publish=forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model=Post
        fields=['title',
                'content',
                'image',
                'draft',
                'publish',
                ]

comments/api/views.py
from rest_framework.generics import (ListAPIView, RetrieveAPIView, DestroyAPIView,
                                     CreateAPIView, RetrieveUpdateAPIView)

from rest_framework.permissions import (IsAuthenticated, IsAdminUser, IsAuthenticatedOrReadOnly, AllowAny)
from rest_framework.filters import (SearchFilter,
                                    OrderingFilter,)
from .serializers import CommentSerializer, CommentDetailSerializer
from comments.models import Comment
from posts.api.permissions import IsOwnerOrReadOnly
from posts.api.pagination import PostLimitOffsetPagination
from django.db.models import Q

#class PostCreateAPIView(CreateAPIView):
    #queryset = Post.objects.all()
    #serializer_class = PostCreateUpdateSerializer
    #permission_classes = [IsAuthenticated]

    #def perform_create(self, serializer):
        #serializer.save(user=self.request.user)

class CommentDetailAPIView(RetrieveAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentDetailSerializer
    lookup_field = 'pk'

#class PostUpdateAPIView(RetrieveUpdateAPIView):
    #queryset = Post.objects.all()
    #serializer_class = PostCreateUpdateSerializer
    #lookup_field = 'slug'
    #permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    #def perform_update(self, serializer):
        #serializer.save(user=self.request.user)

#class PostDeleteAPIView(DestroyAPIView):
 #   queryset = Post.objects.all()
 #  serializer_class = PostDetailSerializer
 #  lookup_field = 'slug'
 #   permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

class CommentListAPIView(ListAPIView):
    serializer_class = CommentSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['content', 'user__first_name']
    pagination_class = PostLimitOffsetPagination
    def get_queryset(self, *args, **kwargs):
        queryset_list = Comment.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(user__first_name__icontains=query)|
                Q(user__last_name__icontains=query)
            ).distinct()
        return queryset_list

comments/views.py
from django.shortcuts import render, get_object_or_404
from comments.models import Comment
from comments.forms import CommentForm
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

def comment_thread(request, id):
    #obj = get_object_or_404(Comment, id=id)
    try:
        obj = Comment.objects.get(id=id)
    except:
        raise Http404

    if not obj.is_parent:
        obj = obj.parent

    content_object = obj.content_object
    content_id = obj.content_object.id
    initial_data ={
            'content_type': obj.content_type,
            'object_id': obj.object_id
        }
    form =CommentForm(request.POST or None, initial=initial_data )
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                                user = request.user,
                                content_type = content_type,
                                object_id = obj_id,
                                content = content_data,
                                parent = parent_obj
        )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    context = {
        'comment': obj,
        'form': form
    }
    return render(request, "comments.html", context)

@login_required(login_url='/login/')
def comment_delete(request, id):
    #obj = get_object_or_404(Comment, id=id)
    try:
        obj = Comment.objects.get(id=id)
    except:
        raise Http404

    if obj.user != request.user:
        #messages.success(request, "you do not have permission")
        #raise Http404
        response = HttpResponse("you do not have permission")
        response.status_code = 403
        return response

    if request.method == 'POST':
        parent_obj_url = obj.content_object.get_absolute_url()
        obj.delete()
        messages.success(request, "Deleted!")
        return HttpResponseRedirect(parent_obj_url)

    context = {
        "object": obj
    }
    return render(request, "confirm_delete.html", context)

posts/api/views.py
from rest_framework.generics import (ListAPIView, RetrieveAPIView, DestroyAPIView,
                                     CreateAPIView, RetrieveUpdateAPIView)

from rest_framework.permissions import (IsAuthenticated, IsAdminUser, IsAuthenticatedOrReadOnly, AllowAny)
from rest_framework.filters import (SearchFilter,
                                    OrderingFilter,)
from posts.api.serializers import PostListSerializer, PostDetailSerializer, PostCreateUpdateSerializer
from posts.models import Post
from .permissions import IsOwnerOrReadOnly
from .pagination import PostLimitOffsetPagination
from django.db.models import Q

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'

class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostLimitOffsetPagination
    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(user__first_name__icontains=query)|
                Q(user__last_name__icontains=query)
            ).distinct()
        return queryset_list

templates/base.html
{%load staticfiles%}
<html>
<head>
    <title>
        {%block head_title%}Demo{%endblock head_title%}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

<!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <style>
        {%block style%}
        {%endblock style%}
    </style>
{%block head_extra%}
{%endblock head_extra%}
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

{%include "messages_display.html"%}
<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'posts:list' %}">Home</a></li>
        {% block post_detail_link %}
        {% endblock %}
        {% if not request.user.is_authenticated %}
            <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
            <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
        {% else %}
            <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
        {% endif %}
    </ol>
    {%block content%}
    {%endblock content%}
</div>

<!--<script>
  $(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "",
      // You can put more options here.

    });
  });
  </script>-->

<script   src="http://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
          crossorigin="anonymous">

</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js">

</script>
<script type="text/javascript">
    $(document).ready(function()
    {
        $(".content-markdown").each(function()
        {
            var content=$(this).text()
            console.log(content)
            var markedContent=marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
        })
        $(".content-markdown img").each(function()
        {
            $(this).addClass("img-responsive");
        })

        var contentInput=$("#id_content");

        function setContent(value)
        {
            var markedContent=marked(value)
            $("#preview-content").html(markedContent)
            $("#preview-content img").each(function()
            {
                $(this).addClass("img-responsive");
            })
        }
        setContent(contentInput.val())
        contentInput.keyup(function()
        {
            var newContent=$(this).val()
            setContent(newContent)
        })

        var titleInput=$("#id_title");
        function setTitle(value)
        {
            $("#preview-title").text(value)
        }
        setTitle(titleInput.val())
        titleInput.keyup(function()
        {
            var newContent=$(this).val()
            setTitle(newContent)
        })

        $(".comment-reply-btn").click(function(event)
        {
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        })
    })

</script>
</body>
</html>

<!-- Latest compiled and minified CSS -->


<!-- Latest compiled and minified JavaScript -->

templates/blog.html
{% load staticfiles %}
{%include 'navbar.html'%}
{%block content%}
    <div class="container">
        <div class="blog-header">
        <p class="lead blog-description"></p>
		<form method="GET" action="" class="row">
         <div class="col-sm-6">
             <div class="input-group">
                <input class="form-control" type="text" name="q" value="{{request.GET.q}}" placeholder="Search Post"/>
                <span class="input-group-btn">
                    <!--<input class="btn btn-default" type="submit" value="Search"/>-->
                    <button class="btn btn-primary" type="submit">Search <i class="fa fa-search" aria-hidden="true"></i></button>
                </span>
             </div>
         </div>
     </form>
      </div>

    {%for obj in object_list%}
      <div class="row">
        <div class="blog-main">
          <div class="col-lg-12 blog-post">
			  <h3 class="blog-post-title"><a href="{{obj.get_absolute_url}}">{{obj.title}}</a></h3>
			  {%if obj.image%}
                    <img src="{{obj.image.url}}" class="img-responsive"/>
                    {%endif%}
			  <div class="caption">
				  {%if obj.draft%}<h3> Draft</h3>{%endif%}
				  {%if obj.publish > today%}<h3>Future Post</h3>{%endif%}
                  <p></p>
            	<p class="blog-post-meta">{{obj.publish}} by {{obj.user.get_username}}</p>
				  <p class="content-markdown">{{obj.content|truncatechars_html:500}}</p>
                        <!--{{obj.get_markdown|truncatechars_html:120}}-->
						<p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a></p>
					</div>
			  		<hr/>
		  </div>
            </div>
        </div>
       {%endfor%}<!-- /.blog-main -->

</div>

<footer class="blog-footer">
   <div class="pagination">
      <span class="step-links">
          <nav>
          <ul class="pager">
        {% if object_list.has_previous %}
          <li><a href="?{{page_request_var}}={{ object_list.previous_page_number }}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">Previous</a></li>
        {% endif %}
         <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>
        {% if object_list.has_next %}
              <li><a href="?page={{ object_list.next_page_number }}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">Next</a></li>
            </ul>
          </nav>
      {% endif %}
     </span>
   </div>
    <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/js2.js' %}"></script>
{%endblock content%}
  </body>
</html>

templates/form.html
{%include "navbar.html"%}
{%load crispy_forms_tags%}

{% block content%}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<form method="post" action="" enctype="multipart/form-data">{%csrf_token%}
    {{form|crispy}}
    <input type="submit" class="btn btn-default" value="{{title}}">
</form>
</div>
{%endblock content%}

templates/messages_display.html
{% if messages %}
<div class="messages">
    <ul class="messages">
    {% for message in messages %}
        <li {%if message.tags%} class="{{ message.tags }}"{%endif%}>{%if "html_safe" in message.tags%}
        {{message|safe}}{%else%}{{message}}{%endif%}
        </li>
    {%endfor%}
    </ul>
{%endif%}

templates/navbar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../favicon.ico"> -->

    <title>
        {%block head_title%}JeevUthan{%endblock head_title%}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/css2.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]<script src="{% static 'js/js1.js"></script><![endif]-->
    <script src="{% static 'js/js1.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>
  </head>

  <body>
  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
  <script   src="http://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
          crossorigin="anonymous">

</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js">

</script>
  <script   src="http://code.jquery.com/jquery-1.12.4.min.js"   integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
          crossorigin="anonymous">

</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous">

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js">

</script>
<script type="text/javascript">
    $(document).ready(function()
    {
        $(".content-markdown").each(function()
        {
            var content=$(this).text()
            console.log(content)
            var markedContent=marked(content)
            console.log(markedContent)
            $(this).html(markedContent)
        })
        $(".content-markdown img").each(function()
        {
            $(this).addClass("img-responsive");
        })

        var contentInput=$("#id_content");

        function setContent(value)
        {
            var markedContent=marked(value)
            $("#preview-content").html(markedContent)
            $("#preview-content img").each(function()
            {
                $(this).addClass("img-responsive");
            })
        }
        setContent(contentInput.val())
        contentInput.keyup(function()
        {
            var newContent=$(this).val()
            setContent(newContent)
        })

        var titleInput=$("#id_title");
        function setTitle(value)
        {
            $("#preview-title").text(value)
        }
        setTitle(titleInput.val())
        titleInput.keyup(function()
        {
            var newContent=$(this).val()
            setTitle(newContent)
        })

        $(".comment-reply-btn").click(function(event)
        {
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        })
    })

</script>
    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item fa fa-home" aria-hidden="true" href="{% url 'posts:list' %}">  Home</a>
		  {% if not request.user.is_authenticated %}
			  <a class="blog-nav-item fa fa-registered" aria-hidden="true" href="{% url 'register' %}">  Register</a>
			  <a class="blog-nav-item fa fa-sign-in" aria-hidden="true" href="{% url 'login' %}">  Login</a>
		  {% else %}
            <a class="blog-nav-item fa fa-plus-circle" aria-hidden="true" href="{% url 'posts:create' %}">  New Post</a>
          	<a class="blog-nav-item pull-right" href="{% url 'logout' %}">Logout  <i class="fa fa-sign-in" aria-hidden="true"></i></a>
		  {% endif %}
		</nav>
      </div>
    </div>
{%block content%}
    {%endblock content%}
{%include "messages_display.html"%}